const animes = [
    {
        name: 'The Boy And The Heron',
        genre: ['Adventure', 'Fantasy', 'Supernatural'],
        type: 'Movie',
        rating: '',
        wiki: '',
        japanese: 'https://fast.wistia.net/embed/iframe/bh7y3nz0oq?seo=true&videoFoam=false',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/j63zZyB/the-boy-and-the-heron.webp',
        duration: '02:03:56',
        download: "https://s3taku.com/download?id=MjI3MzI2&typesub=Gogoanime-SUB&title=Kimitachi+wa+Dou+Ikiru+ka+Episode+1"
    },
    {
        name: 'Suzume No Tojimari',
        genre: ['Adventure', 'Fantasy', 'Supernatural'],
        type: 'Movie',
        rating: '',
        wiki: '',
        japanese: 'https://fast.wistia.net/embed/iframe/u9vakbgihd?seo=true&videoFoam=false',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/6r3PV14/suzume.webp',
        duration: '02:01:28',
        download: 'https://s3taku.com/download?id=MjAzMTM0&typesub=Gogoanime-SUB&title=Suzume+no+Tojimari+Episode+1',
    },
    {
        name: 'Your Name',
        genre: ['Romance', 'Drama', 'Time Travel', 'Supernatural', 'Emotional'],
        type: 'Movie',
        rating: '9.8',
        wiki: 'https://en.m.wikipedia.org/wiki/Your_Name',
        japanese: 'https://fast.wistia.net/embed/iframe/2zh0m22eol?seo=true&videoFoam=false',
        english: 'https://fast.wistia.net/embed/iframe/otcfoxjwje?seo=true&videoFoam=false',
        hindi: 'https://fast.wistia.net/embed/iframe/rr18imoqa5?web_component=true&seo=true',
        img: 'https://i.ibb.co.com/TbN07Ry/your-name.webp',
        duration: '01:46:35',
        download: 'https://s3taku.com/download?id=NzU4ODg=&typesub=Gogoanime-SUB&title=Kimi+no+Na+wa.+Episode+1',
    },
    {
        name: 'Weathering With You',
        genre: ['Romance', 'Fantasy', 'Nature'],
        type: 'Movie',
        rating: '',
        wiki: '',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/Z8sqX5c/weathering-with-you.webp',
        duration: '01:54:00',
        download: 'https://s3taku.com/download?id=MTM5MDA3&typesub=Gogoanime-SUB&title=Tenki+no+Ko+Episode+1',
    },
    {
        name: 'I Want To Eat Your Pancreas',
        genre: ['Romance', 'Drama', 'Emotional'],
        type: 'Movie',
        rating: '',
        wiki: '',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/W5vmJWF/I-want-to-eat-your-pancreas.webp',
        duration: '01:48:00',
        download: 'https://s3taku.com/download?id=MTExNzIz&typesub=Gogoanime-SUB&title=Kimi+no+Suizou+wo+Tabetai+Episode+1',
    },
    {
        name: 'A Silent Voice',
        genre: ['Romance', 'Drama', 'School'],
        type: 'Movie',
        rating: '',
        wiki: '',
        japanese: 'https://fast.wistia.net/embed/iframe/2gwwc5mydi?seo=true&videoFoam=false',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/XDXnRwR/a-silent-voice.webp',
        duration: '02:09:00',
        download: 'https://s3taku.com/download?id=OTgyMzM=&typesub=Gogoanime-SUB&title=Koe+no+Katachi+-+MOVIE+Episode+1',
    },
    {
        name: 'Spirited Away',
        genre: ['Kids', 'Fantasy', 'Adventure'],
        type: 'Movie',
        rating: '',
        wiki: '',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/3dQKzhZ/spirited-away.webp',
        duration: '02:05:00',
        download: 'https://s3taku.com/download?id=MjIxNDM5&typesub=Gogoanime-SUB&title=Sen+to+Chihiro+no+Kamikakushi+Episode+1',
    },
    {
        name: 'A Whisker Away',
        genre: ['Fantasy', 'Romance', 'Magic'],
        type: 'Movie',
        rating: '',
        wiki: '',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/6vKt4bB/a-whisker-away.webp',
        duration: '01:44:00',
        download: 'https://s3taku.com/download?id=MTQxNDAz&typesub=Gogoanime-SUB&title=Nakitai+Watashi+wa+Neko+wo+Kaburu+Episode+1',
    },
    {
        name: 'To Me, The One Who Loved You',
        genre: ['Sci-fi', 'Romance', 'Drama', 'Supernatural'],
        type: 'Movie',
        rating: '',
        wiki: '',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/mcYP0m4/to-me-the-one-who-loved-you.webp',
        duration: '0:0:0',
        download: 'https://s3taku.com/download?id=MjAyMDQ1&typesub=Gogoanime-SUB&title=Kimi+wo+Aishita+Hitori+no+Boku+e+Episode+1',
    },
    {
        name: 'To Every You Ive Loved Before',
        genre: ['Sci-fi', 'Romance', 'Drama', 'Supernatural'],
        type: 'Movie',
        rating: '',
        wiki: '',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/C0csk5D/to-every-you-I-ve-loved-before.webp',
        duration: '0:0:0',
        download: 'https://s3taku.com/download?id=MjAyMTUw&typesub=Gogoanime-SUB&title=Boku+ga+Aishita+Subete+no+Kimi+e+Episode+1',
    },
    {
        name: 'Josse: Tiger And Fish',
        genre: ['Romance', 'Drama', 'Slice Of Life'],
        type: 'Movie',
        rating: '',
        wiki: '',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/hghb4Jc/josse-tiger-and-fish.webp',
        duration: '01:38:00',
        download: 'https://s3taku.com/download?id=MTgxODAx&typesub=Gogoanime-DUB&title=Josee+to+Tora+to+Sakana-tachi+%28Dub%29+Episode+1',
    },
    {
        name: 'Whisper Of The Heart',
        genre: ['Romance', 'Drama', 'Slice Of Life', 'Fantasy'],
        type: 'Movie',
        rating: '',
        wiki: '',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/rpYGKt6/whisper-of-the-heart.webp',
        duration: '01:55:00',
        download: 'https://s3taku.com/download?id=NDAzNjU=&typesub=Gogoanime-SUB&title=Whisper+of+the+Heart+Episode+1',
    },
    {
        name: 'The Cat Returns',
        genre: ['Fantasy', 'Adventure', 'Comedy', 'Family'],
        type: 'Movie',
        rating: '',
        wiki: '',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/3SGm1wg/the-cat-returns.webp',
        duration: '01:14:00',
        download: 'https://s3taku.com/download?id=NDA4MDk=&typesub=Gogoanime-SUB&title=The+Cat+Returns+Episode+1',
    },
    {
        name: 'Ponyo',
        genre: ['Kids', 'Fantasy', 'Adventure', 'Magic'],
        type: 'Movie',
        rating: '',
        wiki: '',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/ZH5vrwq/ponyo.webp',
        duration: '01:55:00',
        download: 'https://s3taku.com/download?id=NDA5Mjk=&typesub=Gogoanime-SUB&title=Ponyo+on+the+Cliff+by+the+Sea+Episode+1',
    },
    {
        name: 'Grave Of The Fireflies',
        genre: ['Drama', 'War', 'Historical', 'Emotional'],
        type: 'Movie',
        rating: '',
        wiki: '',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/0CDSw7P/grave.webp',
        duration: '01:29:00',
        download: 'https://s3taku.com/download?id=NDA3MDM=&typesub=Gogoanime-SUB&title=Grave+of+the+Fireflies+Episode+1',
    },
    {
        name: 'Forest Of The FireFly Light',
        genre: ['Romance', 'Fantasy', 'Supernatural', 'Emotional'],
        type: 'Movie',
        rating: '',
        wiki: '',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/jD8pL9Q/forest-of-the-firefly-light.jpg',
        duration: '00:45:00',
        download: 'https://s3taku.com/download?id=NDI4NTg=&typesub=Gogoanime-SUB&title=Hotarubi+no+Mori+e+%282011%29+Episode+1',
    },
    {
        name: 'Kiki\'s Delivery Service',
        genre: ['Fantasy', 'Slice Of Life', 'Magic',],
        type: 'Movie',
        rating: '',
        wiki: '',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/r3XxPgG/kikis-delivery-service.webp',
        duration: '01:42:00',
        download: 'https://s3taku.com/download?id=OTY3MTM=&typesub=Gogoanime-SUB&title=Majo+no+Takkyuubin+Episode+1',
    },
    {
        name: 'My Neighbor Totoro',
        genre: ['Kids', 'Fantasy', 'Adventure'],
        type: 'Movie',
        rating: '',
        wiki: '',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/7NjCm1s/my-neighbor-totoro.webp',
        duration: '01:26:00',
        download: 'https://s3taku.com/download?id=NDA1OTg=&typesub=Gogoanime-SUB&title=My+Neighbor+Totoro+Episode+1',
    },
    {
        name: 'The Wind Rises',
        genre: ['Drama', 'Historical', 'Romance', 'War'],
        type: 'Movie',
        rating: '',
        wiki: '',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/tBZ4h7w/the-wind-rises.webp',
        duration: '02:06:00',
        download: 'https://s3taku.com/download?id=NDQ3MTM=&typesub=Gogoanime-SUB&title=Kaze+Tachinu+%28The+Wind+Rises%29+Episode+1',
    },
    {
        name: 'Flavors Of Youth',
        genre: ['Slice Of Life', 'Drama', 'Romance', 'Emotional'],
        type: 'Movie',
        rating: '',
        wiki: '',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/xFSXBY3/flavors-of-youth.webp',
        duration: '01:15:00',
        download: 'https://s3taku.com/download?id=MTA3MjQy&typesub=Gogoanime-SUB&title=Shikioriori+Episode+0',
    },
    {
        name: 'Nausicaa Of The Valley Of The Wind',
        genre: ['Fantasy', 'Adventure', 'Sci-fi'],
        type: 'Movie',
        rating: '',
        wiki: '',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/PTGt9Rg/nausicaa.webp',
        duration: '01:57:00',
        download: 'https://s3taku.com/download?id=NDA1NzM=&typesub=Gogoanime-SUB&title=Nausicaa+of+the+Valley+of+the+Wind+Episode+1',
    },
    {
        name: 'Laputa: Castle In The Sky',
        genre: ['Fantasy', 'Adventure', 'Romance', 'action'],
        type: 'Movie',
        rating: '',
        wiki: '',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/pzT0Yfd/laputa-castle-in-the-sky.webp',
        duration: '02:04:00',
        download: 'https://s3taku.com/download?id=NDA2NTg=&typesub=Gogoanime-SUB&title=Laputa%3A+Castle+in+the+Sky+Episode+1',
    },
    {
        name: 'From Up On Poppy Hill',
        genre: ['Romance', 'Drama', 'School', 'Slice Of Life'],
        type: 'Movie',
        rating: '',
        wiki: '',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/N2JK37J/from-up-on-poppy-hill.webp',
        duration: '01:31:00',
        download: 'https://s3taku.com/download?id=NDA2NjA=&typesub=Gogoanime-SUB&title=Kokurikozaka+Kara+Episode+1',
    },
    {
        name: 'The Garden Of Words',
        genre: ['Romance', 'Drama', 'Nature', 'Emotional'],
        type: 'Movie',
        rating: '',
        wiki: '',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/TwXqZGz/the-garden-of-words.webp',
        duration: '00:46:00',
        download: 'https://s3taku.com/download?id=NDA2NTk=&typesub=Gogoanime-SUB&title=Kotonoha+no+Niwa+Episode+1',
    },
    {
        name: 'Princess Mononoke',
        genre: ['Adventure', 'Fantasy', 'Supernatural','Nature'],
        type: 'Movie',
        rating: '',
        wiki: '',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/vJNJkvM/princess-mononoke.webp',
        duration: '02:25:00',
        download: 'https://s3taku.com/download?id=NDA0ODU=&typesub=Gogoanime-SUB&title=Princess+Mononoke+Episode+1',
    },
    {
        name: 'Porco Rosso',
        genre: ['Action', 'Adventure', 'Fantasy', 'Comedy'],
        type: 'Movie',
        rating: '',
        wiki: '',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/0yxMGPc/porco-rosso.webp',
        duration: '01:29:00',
        download: 'https://s3taku.com/download?id=NDA5Mjg=&typesub=Gogoanime-SUB&title=Porco+Rosso+Episode+1',
    },
    {
        name: 'The Place Promised In Our Early Days',
        genre: ['Romance', 'Drama', 'Sci-fi', 'Emotional'],
        type: 'Movie',
        rating: '',
        wiki: '',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/zhfcQQz/the-place-promised-in-our-early-days.webp',
        duration: '01:31:00',
        download: 'https://s3taku.com/download?id=NDA0MDM=&typesub=Gogoanime-SUB&title=The+Place+Promised+in+Our+Early+Days+Episode+1',
    },
    {
        name: '5 Centimeters Per Second',
        genre: ['Romance', 'Slice Of Life', 'Drama', 'Emotional'],
        type: 'Movie',
        rating: '',
        wiki: '',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/VBLdBFf/5-centimeters-per-second.webp',
        duration: '01:03:00',
        download: 'https://s3taku.com/download?id=NDA3ODE=&typesub=Gogoanime-SUB&title=5+Centimeters+Per+Second+Episode+1',
    },
    {
        name: 'Hello World',
        genre: ['Sci-fi', 'Romance', 'Time Travel'],
        type: 'Movie',
        rating: '',
        wiki: '',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/p4Tjw7B/hello-world.webp',
        duration: '01:38:00',
        download: 'https://s3taku.com/download?id=MTM4NjM2&typesub=Gogoanime-SUB&title=Hello+World+Episode+1',
    },
    {
        name: 'Wolf Children',
        genre: ['Fantasy', 'Drama', 'Slice Of Life', 'Family'],
        type: 'Movie',
        rating: '',
        wiki: '',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/Wp9g8M4/wolf-children.webp',
        duration: '01:57:00',
        download: 'https://s3taku.com/download?id=NDA1Mzk=&typesub=Gogoanime-SUB&title=Ookami+Kodomo+no+Ame+to+Yuki+Episode+1',
    },
    {
        name: 'Heidi',
        genre: ['Kids', 'Nature', 'Rural'],
        type: 'Movie',
        rating: '',
        wiki: '',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/zNdHZ01/heidi.jpg',
        duration: '01:29:00',
        download: 'https://s3taku.com/download?id=MTI5MDgw&typesub=Gogoanime-SUB&title=Alps+no+Shoujo+Heidi+%281979%29+Episode+1',
    },
    {
        name: 'Tamako Love Story',
        genre: ['Romance', 'Drama', 'School'],
        type: 'Movie',
        rating: '',
        wiki: '',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/2PprGch/tamako-love-story.webp',
        duration: '01:23:00',
        download: 'https://s3taku.com/download?id=NDgyOTE=&typesub=Gogoanime-SUB&title=Tamako+Love+Story+Episode+1',
    },
    {
        name: 'The Anthem Of The Heart',
        genre: ['School', 'Drama', 'Romance'],
        type: 'Movie',
        rating: '',
        wiki: '',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/mvfMHct/the-anthem-of-the-heart.webp',
        duration: '0:0:0',
        download: 'https://s3taku.com/download?id=NzEzMjY=&typesub=Gogoanime-SUB&title=Kokoro+ga+Sakebitagatterunda.+Episode+1',
    },
    {
        name: 'Howl\'s Moving Castle',
        genre: ['Romance', 'Fantasy', 'Adventure', 'Magic'],
        type: 'Movie',
        rating: '',
        wiki: '',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/jysgvw1/howls-moving-castle.webp',
        duration: '0:0:0',
        download: 'https://s3taku.com/download?id=NDA2ODU=&typesub=Gogoanime-SUB&title=Howls+Moving+Castle+Episode+1',
    },
    {
        name: 'The Children Who Chase Lost Voices',
        genre: ['Adventure', 'Fantasy', 'Mystery'],
        type: 'Movie',
        rating: '',
        wiki: '',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/KcPtNzM/the-children-who-chase-lost-voices.webp',
        duration: '0:0:0',
        download: 'https://s3taku.com/download?id=NDMyMjI=&typesub=Gogoanime-SUB&title=Children+who+Chase+Lost+Voices+Episode+1',
    },
    {
        name: 'Summer Wars',
        genre: ['Sci-fi', 'Fantasy', 'Drama', 'Adventure'],
        type: 'Movie',
        rating: '',
        wiki: '',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/t3J7sqB/summer-wars.webp',
        duration: '0:0:0',
        download: 'https://s3taku.com/download?id=NDA0MjA=&typesub=Gogoanime-SUB&title=Summer+Wars+Episode+1',
    },
    {
        name: 'The Tale Of Princess Kaguya',
        genre: ['Kids', 'Fantasy', 'Fairy Tale'],
        type: 'Movie',
        rating: '',
        wiki: '',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/tzfB3Dp/the-tale-of-princess-kaguya.webp',
        duration: '0:0:0',
        download: 'https://s3taku.com/download?id=NDg5NTk=&typesub=Gogoanime-SUB&title=Kaguya-hime+no+Monogatari+Episode+1',
    },
    {
        name: 'The Girl Who Leapt Through Time',
        genre: ['Time Travel', 'Sci-fi', 'Romance', 'Drama'],
        type: 'Movie',
        rating: '',
        wiki: '',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/qYh2r44/the-girl-who-leapt-through-time.webp',
        duration: '0:0:0',
        download: 'https://s3taku.com/download?id=NDMwMDA=&typesub=Gogoanime-SUB&title=Toki+Wo+Kakeru+Shoujo+Episode+1',
    },
    {
        name: 'Summer Ghost',
        genre: ['Supernatural', 'Drama', 'Romance', 'Emotional'],
        type: 'Movie',
        rating: '',
        wiki: '',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/SVq56DM/summer-ghost.webp',
        duration: '0:0:0',
        download: 'https://s3taku.com/download?id=MTgzNTkw&typesub=Gogoanime-SUB&title=Summer+Ghost+Episode+1',
    },
    {
        name: 'Fireworks',
        genre: ['Romance', 'Drama', 'Slice Of Life'],
        type: 'Movie',
        rating: '',
        wiki: '',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/yVCW7fC/fireworks.webp',
        duration: '0:0:0',
        download: 'https://s3taku.com/download?id=MTA1MTQ1&typesub=Gogoanime-SUB&title=Uchiage+Hanabi%2C+Shita+kara+Miru+ka%3F+Yoko+kara+Miru+ka%3F+Episode+1',
    },
    {
        name: 'I\'ve Always Liked You',
        genre: ['Romance', 'Drama', 'Slice Of Life', 'School'],
        type: 'Movie',
        rating: '',
        wiki: '',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/MnKPVYN/ive-always-liked-you.webp',
        duration: '0:0:0',
        download: 'https://s3taku.com/download?id=NzcxMjM=&typesub=Gogoanime-SUB&title=Zutto+Mae+kara+Suki+deshita.%3A+Kokuhaku+Jikkou+Iinkai+-+MOVIE+Episode+1',
    },
    {
        name: 'Her Blue Sky',
        genre: ['Romance', 'Drama', 'Slice Of Life', 'Nature'],
        type: 'Movie',
        rating: '',
        wiki: '',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/CsVkpTY/her-blue-sky.webp',
        duration: '0:0:0',
        download: 'https://s3taku.com/download?id=MTQwOTcx&typesub=Gogoanime-SUB&title=Sora+no+Aosa+wo+Shiru+Hito+yo+Episode+1',
    },
    {
        name: 'Drifting Home',
        genre: ['Kids', 'Fantasy', 'Adventure'],
        type: 'Movie',
        rating: '',
        wiki: '',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/ckhGsXJ/drifting-home.webp',
        duration: '0:0:0',
        download: 'https://s3taku.com/download?id=MTkyMzI0&typesub=Gogoanime-SUB&title=Ame+wo+Tsugeru+Hyouryuu+Danchi+Episode+1',
    },
    {
        name: 'Voices Of A Distant Star',
        genre: ['Sci-fi', 'Drama', 'Romance', 'Space'],
        type: 'Movie',
        rating: '',
        wiki: '',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/WDpLfXd/voices-of-a-distant-star.webp',
        duration: '0:0:0',
        download: 'https://s3taku.com/download?id=NDA3NTc=&typesub=Gogoanime-SUB&title=Voices+of+a+Distant+Star+Episode+1',
    },
    {
        name: 'Cross Road',
        genre: ['School', 'Drama', 'Slice Of Life', 'Romance'],
        type: 'Movie',
        rating: '',
        wiki: '',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/DbHHry7/cross-road.webp',
        duration: '0:0:0',
        download: 'https://s3taku.com/download?id=NDIxNDg=&typesub=Gogoanime-SUB&title=Cross+Road+Episode+1',
    },
    {
        name: 'When Marnie Was There',
        genre: ['Fantasy', 'Mystery', 'Emotional', 'Nature'],
        type: 'Movie',
        rating: '',
        wiki: '',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/Y8Rdg3L/when-marnie-was-there.webp',
        duration: '0:0:0',
        download: 'https://s3taku.com/download?id=NTEyNzc=&typesub=Gogoanime-SUB&title=Omoide+no+Marnie+Episode+1',
    },
    {
        name: 'Only Yesterday',
        genre: ['Rural', 'Drama', 'Slice Of Life','Nature'],
        type: 'Movie',
        rating: '',
        wiki: '',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/gTZpLRd/only-yesterday.webp',
        duration: '0:0:0',
        download: 'https://s3taku.com/download?id=NDA1NDA=&typesub=Gogoanime-SUB&title=Only+Yesterday+Episode+1',
    },
    {
        name: 'Twilight',
        genre: ['Romance', 'School', 'Nature'],
        type: 'Movie',
        rating: '',
        wiki: '',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/rxfg9mt/twilight.webp',
        duration: '0:0:0',
        download: 'https://s3taku.com/download?id=MTQyMTE1&typesub=Gogoanime-SUB&title=Hakubo+Episode+1',
    },
    {
        name: 'Penguin Highway',
        genre: ['Kids', 'Adventure', 'Fantasy'],
        type: 'Movie',
        rating: '',
        wiki: '',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/VH2VwVw/penguin-highway.webp',
        duration: '0:0:0',
        download: 'https://s3taku.com/download?id=MTEzOTQw&typesub=Gogoanime-SUB&title=Penguin+Highway+Episode+1',
    },
    {
        name: 'Fortune Favors Lady Nikuko',
        genre: ['Slice Of Life', 'Family', 'Drama'],
        type: 'Movie',
        rating: '',
        wiki: '',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/QNQwk0w/fortune-favors-lady-nikuko.webp',
        duration: '0:0:0',
        download: 'https://s3taku.com/download?id=MTg2OTcy&typesub=Gogoanime-SUB&title=Gyokou+no+Nikuko-chan+Episode+1',
    },
    {
        name: 'Maquia: When The Promised Flower Blooms',
        genre: ['Drama', 'Fantasy', 'Supernatural', 'Emotional'],
        type: 'Movie',
        rating: '',
        wiki: '',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/801853G/maquia.webp',
        duration: '0:0:0',
        download: 'https://s3taku.com/download?id=MTEyNTEy&typesub=Gogoanime-SUB&title=Sayonara+no+Asa+ni+Yakusoku+no+Hana+wo+Kazarou+Episode+1',
    },
    {
        name: 'Ride Your Wave',
        genre: ['Romance', 'Emotional', 'Drama', 'Fantasy'],
        type: 'Movie',
        rating: '',
        wiki: '',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/KxyxCYQ/ride-your-wave.webp',
        duration: '0:0:0',
        download: 'https://s3taku.com/download?id=MTM1NDUy&typesub=Gogoanime-SUB&title=Kimi+to%2C+Nami+ni+Noretara+Episode+1',
    },
    {
        name: 'Over The Sky',
        genre: ['Fantasy', 'Adventure', 'Drama', 'Romance'],
        type: 'Movie',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/cYwPgNS/over-the-sky.webp',
        duration: '0:0:0',
        download: 'https://s3taku.com/download?id=MTczMzc1&typesub=Gogoanime-SUB&title=Kimi+wa+Kanata+Episode+1',
    },
    {
        name: 'Mai Mai Miracle',
        genre: ['Kids', 'Rural', 'Slice Of Life', 'Fantasy'],
        type: 'Movie',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/m5p0PK5/mai-mai-miracle.webp',
        duration: '0:0:0',
        download: 'https://s3taku.com/download?id=NDI5OTE=&typesub=Gogoanime-SUB&title=Mai-Mai+Miracle+%282009%29+Episode+1',
    },
    {
        name: 'Summer Days With Coo',
        genre: ['Fantasy', 'Family', 'Adventure', 'Slice Of Life'],
        type: 'Movie',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/vxy3fXv/summer-days-with-coo.webp',
        duration: '0:0:0',
        download: 'https://s3taku.com/download?id=MTM2NzY3&typesub=Gogoanime-SUB&title=Kappa+no+Coo+to+Natsuyasumi+Episode+1',
    },
    {
        name: 'Sword Of The Stranger',
        genre: ['Action', 'Adventure', 'Historical', 'Samurai'],
        type: 'Movie',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/MDGvBnc/sword-of-the-stranger.webp',
        duration: '0:0:0',
        download: 'https://s3taku.com/download?id=NDA0MTU=&typesub=Gogoanime-SUB&title=Sword+of+the+Stranger+Episode+1',
    },
    {
        name: 'Okko\'s Inn',
        genre: ['Fantasy', 'Drama', 'Supernatural'],
        type: 'Movie',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/hCqpGQK/okkos-inn.webp',
        duration: '0:0:0',
        download: 'https://s3taku.com/download?id=MTI1MjM2&typesub=Gogoanime-SUB&title=Wakaokami+wa+Shougakusei%21+Movie+Episode+1',
    },
    {
        name: 'A Letter To Momo',
        genre: ['Fantasy', 'Drama', 'Family', 'Supernatural'],
        type: 'Movie',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/L8Hdt5T/a-letter-to-momo.webp',
        duration: '0:0:0',
        download: 'https://s3taku.com/download?id=NDA1OTk=&typesub=Gogoanime-SUB&title=Momo+e+no+Tegami+Episode+1',
    },
    {
        name: 'Welcome To The Space Show',
        genre: ['Fantasy', 'Adventure', 'Space', 'Sci-fi'],
        type: 'Movie',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/1sVZgbK/welcome-to-the-space-show.webp',
        duration: '0:0:0',
        download: 'https://s3taku.com/download?id=MTQ3ODI1&typesub=Gogoanime-SUB&title=Uchuu+Show+e+Youkoso+Episode+1',
    },
    {
        name: 'Child Of Kamiari Month',
        genre: ['Fantasy', 'Adventure', 'Family', 'Drama'],
        type: 'Movie',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/G9sDGFj/child-of-kaminari-month.webp',
        duration: '0:0:0',
        download: 'https://s3taku.com/download?id=MTgwMjQ0&typesub=Gogoanime-SUB&title=Kamiarizuki+no+Kodomo+Episode+1',
    },
    {
        name: 'Grandfather\'s Lamp',
        genre: ['Drama', 'Historical', 'Rural', 'Family'],
        type: 'Movie',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/Vq87VwK/grandfathers-lamp.webp',
        duration: '0:0:0',
        download: 'https://s3taku.com/download?id=MTIxODAw&typesub=Gogoanime-SUB&title=Ojiisan+no+Lamp+Episode+1',
    },
    {
        name: 'White Bird',
        genre: ['Fantasy', 'Adventure', 'Drama'],
        type: 'Movie',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/qy4X3PZ/white-bird.webp',
        duration: '0:0:0',
        download: 'https://s3taku.com/download?id=MTY0MDI4&typesub=Gogoanime-SUB&title=Bai+Niao+Episode+1',
    },
    {
        name: 'The Night Is Short, Walk On Girl',
        genre: ['Romance', 'Fantasy', 'Comedy', 'Slice Of Life'],
        type: 'Movie',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/cyLSNhM/the-night-is-short-walk-on-girl.webp',
        duration: '0:0:0',
        download: 'https://s3taku.com/download?id=MTAyMzA0&typesub=Gogoanime-SUB&title=Yoru+wa+Mijikashi+Arukeyo+Otome+Episode+1',
    },
    {
        name: 'Patema Inverted',
        genre: ['Sci-fi', 'Adventure', 'Romance'],
        type: 'Movie',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/X8h4XTL/patema-inverted.webp',
        duration: '0:0:0',
        download: 'https://s3taku.com/download?id=NDMzOTE=&typesub=Gogoanime-SUB&title=Sakasama+no+Patema+Episode+1',
    },
    {
        name: 'The Secret World Of Arrietty',
        genre: ['Fantasy', 'Adventure', 'Family', 'Slice Of Life'],
        type: 'Movie',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/ChTcmrJ/the-secret-world-of-arrietty.webp',
        duration: '0:0:0',
        download: 'https://s3taku.com/download?id=NzQyMzc=&typesub=Gogoanime-SUB&title=Karigurashi+no+Arrietty+Episode+1',
    },
    {
        name: 'Barefoot Gen',
        genre: ['Drama', 'Historical', 'War', 'Emotional'],
        type: 'Movie',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/nkZm3sY/barefoot-gen.webp',
        duration: '0:0:0',
        download: 'https://s3taku.com/download?id=MTQxOTIy&typesub=Gogoanime-SUB&title=Hadashi+no+Gen+Episode+1',
    },
    {
        name: 'Tales From Earthsea',
        genre: ['Fantasy', 'Adventure', 'Drama', 'Magic'],
        type: 'Movie',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/ftNMJhD/tales-from-earthsea.webp',
        duration: '0:0:0',
        download: 'https://s3taku.com/download?id=NDA0MTQ=&typesub=Gogoanime-SUB&title=Tales+From+Earthsea+Episode+1',
    },
    {
        name: 'Paprika',
        genre: ['Sci-fi', 'Mystery', 'Psychological'],
        type: 'Movie',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/jkFYCVv/paprika.webp',
        duration: '0:0:0',
        download: 'https://s3taku.com/download?id=NDA1Mzc=&typesub=Gogoanime-SUB&title=Paprika+Episode+1',
    },
    {
        name: 'Typhoon Noruda',
        genre: ['Fantasy', 'Nature', 'Drama', 'Sci-fi'],
        type: 'Movie',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/Bc7Yd4F/typhoon-noruda.webp',
        duration: '0:0:0',
        download: 'https://s3taku.com/download?id=Njg2MTk=&typesub=Gogoanime-SUB&title=Taifuu+no+Noruda+Episode+1',
    },
    {
        name: 'The Case Of Hana And Alice',
        genre: ['Mystery', 'Drama', 'Romance', 'Slice Of Life'],
        type: 'Movie',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/Ws38sF9/the-case-of-hana-and-alice.webp',
        duration: '0:0:0',
        download: 'https://s3taku.com/download?id=Njg5NDY=&typesub=Gogoanime-SUB&title=Hana+to+Alice%3A+Satsujin+Jiken+Episode+1',
    },
    {
        name: 'Ocean Waves',
        genre: ['Drama', 'Romance', 'Slice Of Life'],
        type: 'Movie',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/2jQ183d/ocean-waves.webp',
        duration: '0:0:0',
        download: 'https://s3taku.com/download?id=NDA1NjQ=&typesub=Gogoanime-SUB&title=Ocean+Waves+Episode+1',
    },
    {
        name: 'The Tunnel To Summer, The Exit Of Goodbye',
        genre: ['Romance', 'Time Travel', 'Drama', 'Sci-fi'],
        type: 'Movie',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/C8JMDvC/the-tunnel-to-summer-the-exit-of-goodbye.webp',
        duration: '0:0:0',
        download: 'https://s3taku.com/download?id=MjA1MzE2&typesub=Gogoanime-SUB&title=Natsu+e+no+Tunnel%2C+Sayonara+no+Deguchi+Episode+1',
    },
    {
        name: 'Koi Sento',
        genre: ['Romance', 'Fantasy', 'Sci-fi'],
        type: 'Movie',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/7X9Jd1Y/koi-sento.webp',
        duration: '0:0:0',
        download: 'https://s3taku.com/download?id=OTY1OTE=&typesub=Gogoanime-DUB&title=Koi%E2%98%86Sento+%28Dub%29+Episode+1',
    },
    {
        name: 'Rain In Sunshine',
        genre: ['Romance', 'Drama', 'Emotional', 'Kids'],
        type: 'Movie',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/CtTknRc/rain-in-sunshine.webp',
        duration: '0:0:0',
        download: 'https://s3taku.com/download?id=NjA0MzY=&typesub=Gogoanime-SUB&title=Hinata+no+Aoshigure+Episode+1',
    },
    {
        name: 'The Boy And The Beast',
        genre: ['Fantasy', 'Adventure', 'Drama', 'Action'],
        type: 'Movie',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/ZSf9CxM/the-boy-and-the-beast.webp',
        duration: '0:0:0',
        download: 'https://s3taku.com/download?id=NzExNzA=&typesub=Gogoanime-SUB&title=Bakemono+no+Ko+Episode+1',
    },
    {
        name: 'A Wind Named Amnesia',
        genre: ['Sci-fi', 'Fantasy', 'Adventure', 'Rural'],
        type: 'Movie',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/XbvpqX4/a-wind-named-amnesia.webp',
        duration: '0:0:0',
        download: 'https://s3taku.com/download?id=MjA1Nzk4&typesub=Gogoanime-SUB&title=Kaze+no+Na+wa+Amnesia+Episode+1',
    },
    {
        name: 'Words Bubble Up Like Soda Pop',
        genre: ['Romance', 'Slice Of Life', 'Drama', 'Music'],
        type: 'Movie',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/Z6tDZsX/words-bubble-up-like-soda-pop.webp',
        duration: '0:0:0',
        download: 'https://s3taku.com/download?id=MTY2MTQz&typesub=Gogoanime-SUB&title=Cider+no+You+ni+Kotoba+ga+Wakiagaru+Episode+1',
    },
    {
        name: 'Belle',
        genre: ['Fantasy', 'Music', 'Sci-fi', 'Drama'],
        type: 'Movie',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/1M9r8v4/belle.webp',
        duration: '0:0:0',
        download: 'https://s3taku.com/download?id=MTcyMTQ1&typesub=Gogoanime-SUB&title=Ryuu+to+Sobakasu+no+Hime+Episode+1',
    },
    {
        name: 'Bubble',
        genre: ['Sci-fi', 'Romance', 'Fantasy', 'Adventure'],
        type: 'Movie',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/0ys4jbR/bubble.webp',
        duration: '0:0:0',
        download: 'https://s3taku.com/download?id=MTg1MTMy&typesub=Gogoanime-SUB&title=Bubble+Episode+1',
    },
    {
        name: 'Miss Hokusai',
        genre: ['Historical', 'Drama', 'Slice Of Life', 'Rural'],
        type: 'Movie',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/hMYxRMz/miss-hokusai.webp',
        duration: '0:0:0',
        download: 'https://s3taku.com/download?id=NzA1ODE=&typesub=Gogoanime-SUB&title=Sarusuberi%3A+Miss+Hokusai+Episode+1',
    },
    {
        name: 'Space Brothers',
        genre: ['Sci-fi', 'Space', 'Drama', 'Slice Of Life'],
        type: 'Movie',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/TrGwq65/space-brothers.webp',
        duration: '0:0:0',
        download: '',
    },
    {
        name: 'In This Corner Of The World',
        genre: ['Historical', 'Drama', 'War', 'Slice Of Life'],
        type: 'Movie',
        japanese: 'https://iframe.mediadelivery.net/embed/307818/aacc97b8-ef42-4676-859c-2c2b0b880a54?autoplay=true&loop=false&muted=false&preload=true&responsive=true',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/2q6VK2v/in-this-corner-of-the-world.webp',
        duration: '0:0:0',
        download: 'https://s3taku.com/download?id=MTAxNzcx&typesub=Gogoanime-SUB&title=Kono+Sekai+no+Katasumi+ni+Episode+1',
    },
    {
        name: 'Anohana: Movie',
        genre: ['Drama', 'Supernatural', 'Slice Of Life', 'Emotional'],
        type: 'Movie',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/58hmsqn/anohana.webp',
        duration: '0:0:0',
        download: 'https://s3taku.com/download?id=NDIxOTg=&typesub=Gogoanime-SUB&title=AnoHana+The+Movie+Episode+1',
    },
    {
        name: 'GoodBye! Don Gleas',
        genre: ['Adventure', 'Drama', 'Slice Of Life', 'Emotional'],
        type: 'Movie',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/0F464Nh/goodbye-don-gleas.webp',
        duration: '0:0:0',
        download: 'https://s3taku.com/download?id=MTk1NTY1&typesub=Gogoanime-SUB&title=Goodbye%2C+Don+Glees%21+Episode+1',
    },
    {
        name: 'Colorful',
        genre: ['Drama', 'Supernatural', 'Psychological', 'Slice Of Life'],
        type: 'Movie',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/F3XJNNh/colorful.webp',
        duration: '0:0:0',
        download: 'https://s3taku.com/download?id=MTEyNTI4&typesub=Gogoanime-SUB&title=Colorful+%28Movie%29+Episode+1',
    },
    {
        name: 'Hal',
        genre: ['Sci-fi', 'Romance', 'Drama', 'Emotional'],
        type: 'Movie',
        japanese: '',
        english: '',
        hindi: '',
        img: 'https://i.ibb.co.com/F3LSCxG/hal.webp',
        duration: '0:0:0',
        download: 'https://s3taku.com/download?id=NDE0Mjk=&typesub=Gogoanime-SUB&title=Hal+Episode+1',
    },
   /* {
        name: '',
        genre: ['', '', ''],
        type: 'Movie',
        japanese: '',
        english: '',
        hindi: '',
        img: 'Images/.webp',
        duration: '0:0:0',
        download: '',
    }, */
    
    
    
    
    // Add more anime objects here
];
